name: rag-demo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - pandas
  - faiss-cpu
  - requests
  - lxml
  - beautifulsoup4
  - selectolax
  - readability-lxml
  - tiktoken
  - pydantic
  - python-dotenv
  - rich
  - pip
  - pip:
      - langchain==0.3.27
      - langchain-core==0.3.76
      - langchain-community
      - langchain-openai
      - langchain-text-splitters
